### login (receiving token)
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "123"
}

### redirect to protected homepage after received token
GET http://localhost:3000/protectedHomepageTest HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwZjg0NTNmNDVmZWQwMjc1ODA0NzY4MCIsInVzZXJuYW1lIjoibWluaCIsInBhc3N3b3JkIjoiJDJiJDEwJGFzeWlsZnF1TmpYYnRPOXpWNWgxaC44MklBRE5IRnAyZy9ZQVByU1ZwYkZNUmJFZzBGb2VTIiwiX192IjowfSwiaWF0IjoxNjI2OTAwMTUzLCJleHAiOjE2MjY5MDAxODN9.iRZ1TZ3P4JXFYr9NTeAA8C9bSUZZ5BRnx0V7fStRIB8

### //not an email, short psw error
POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "username": "minh",
    "password": "123"
}

### //username already taken error
POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "username": "minh",
    "password": "123"
}

### //creating marker
POST http://localhost:3000/marker/create HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwZmRkNWJlYmViODU4MmI2NGU5MWJhMiIsInVzZXJuYW1lIjoidGVzdCIsInBhc3N3b3JkIjoiJDJiJDEwJHVtQkd4M3hCdUpHek1CLlkuUk84SGViSHhBTVlNVkVDWEhqb3JZa3hrZk9wR1VocWtJYUxhIiwiX192IjowfSwiaWF0IjoxNjI3MjQ4MDg3LCJleHAiOjE2MjcyNTE2ODd9.mBglKfAClOAFzLx31XcKeiUpiUrfJgUcF-KzWSxp9pY

{
    "user": "60fdd5bebeb8582b64e91ba2",
    "lat": 49.44007,
    "lng": 19.1636761,
    "name":"testmarker" ,
    "description":"plzzzz work"
}

### //fetching markers
GET http://localhost:3000/markers

### //fetching markers BY FRIEND (and own markers)
GET http://localhost:3000/markers/user/friends/61045c49d13bcf23a05a0030

### //fetching markers by user
GET http://localhost:3000/markers/user/61045c49d13bcf23a05a0030/

### //deleting marker
DELETE http://localhost:3000/marker/60fdb668bd7ef724907cf17f/delete HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwZjg0NTNmNDVmZWQwMjc1ODA0NzY4MCIsInVzZXJuYW1lIjoibWluaCIsInBhc3N3b3JkIjoiJDJiJDEwJGFzeWlsZnF1TmpYYnRPOXpWNWgxaC44MklBRE5IRnAyZy9ZQVByU1ZwYkZNUmJFZzBGb2VTIiwiX192IjowfSwiaWF0IjoxNjI3MjM5ODg5LCJleHAiOjE2MjcyNDM0ODl9.Y6uthlUSzOxKWCO8jsUWM-C_dd37gCRp7SeVJ4YWNlw


### //liking a marker
PATCH http://localhost:3000/marker/60fdd6af2d462f3aa060849e/like HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwZmRkNWJlYmViODU4MmI2NGU5MWJhMiIsInVzZXJuYW1lIjoidGVzdCIsInBhc3N3b3JkIjoiJDJiJDEwJHVtQkd4M3hCdUpHek1CLlkuUk84SGViSHhBTVlNVkVDWEhqb3JZa3hrZk9wR1VocWtJYUxhIiwiX192IjowfSwiaWF0IjoxNjI3MjQ4MDg3LCJleHAiOjE2MjcyNTE2ODd9.mBglKfAClOAFzLx31XcKeiUpiUrfJgUcF-KzWSxp9pY

{
    "likes": ["60fdd5bebeb8582b64e91ba2"]
}

### //bookmark a marker
PATCH http://localhost:3000/marker/60f8453f45fed02758047680/bookmark HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImJvb2ttYXJrcyI6W10sIl9pZCI6IjYwZmRkNWJlYmViODU4MmI2NGU5MWJhMiIsInVzZXJuYW1lIjoidGVzdCIsInBhc3N3b3JkIjoiJDJiJDEwJHVtQkd4M3hCdUpHek1CLlkuUk84SGViSHhBTVlNVkVDWEhqb3JZa3hrZk9wR1VocWtJYUxhIiwiX192IjowfSwiaWF0IjoxNjI3Mjk5MDUxLCJleHAiOjE2MjczMDI2NTF9.8Ii5k0GDkAdNFouE1g82bMH800KfvipBWWWOdQzrdNQ

{
    "bookmarks": ["60fd8616c6046133305cd1d6", "60fd7ca7c6046133305cd1d0"]
}

### //get comments for a marker
GET http://localhost:3000/marker/60fec1df7c57db3cccceb815/comments HTTP/1.1
content-type: application/json

### //get all users
GET http://localhost:3000/users

### //get 1 user
GET http://localhost:3000/user/6107f0780510112ef06bb4da

### //accept friend request and sending back updated user
PATCH  http://localhost:3000/user/61045c49d13bcf23a05a0030/61046c466d816205d8294435 HTTP/1.1
content-type: application/json
Authorization: 

{
    "friendsReceiver" : ["61045d09d13bcf23a05a0046", "6104676609b98f125cef7512", "610469240f0c092820599b00", "61046c466d816205d8294435"],
    "friendRequestsReceiver" : [],
    "frinedsSender": ["61045c49d13bcf23a05a0030"]
}